### ISSUE TITLE
Can't use AIRCAST_VAR

### ISSUE THREAD

**Issue by hipstersmoothie** [1activegeek/docker-airconnect#24]
Hey! Thanks for the container. 

I'm having trouble passing any options to airconnect using the AIRCAST_VAR variable.

Here is what my docker-compose config looks like. originally I was trying to us `-x` but switched to `-d` to try to debug.

```yml
version: '2'
services:
  airconnect:
    image: 1activegeek/airconnect:latest
    container_name: airconnect
    restart: always
    network_mode: host
    environment:
      - AIRCAST_VAR='-d all=debug'
```

Anytime I run `docker-compose up airconnect` (to debug) and have `AIRCAST_VAR` set to any of the flags I get the following output.

```txt
airconnect    | 2021-06-20 00:07:33,927 CRIT Supervisor running as root (no user in config file)
airconnect    | 2021-06-20 00:07:33,929 INFO supervisord started with pid 287
airconnect    | 2021-06-20 00:07:34,932 INFO spawned: 'airupnp-x86-64' with pid 293
airconnect    | 2021-06-20 00:07:34,934 INFO spawned: 'aircast-x86-64' with pid 294
airconnect    | 2021-06-20 00:07:34,940 INFO exited: aircast-x86-64 (exit status 1; not expected)
airconnect    | 2021-06-20 00:07:36,048 INFO success: airupnp-x86-64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
airconnect    | 2021-06-20 00:07:36,050 INFO spawned: 'aircast-x86-64' with pid 308
airconnect    | 2021-06-20 00:07:36,056 INFO exited: aircast-x86-64 (exit status 1; not expected)
airconnect    | 2021-06-20 00:07:38,059 INFO spawned: 'aircast-x86-64' with pid 309
airconnect    | 2021-06-20 00:07:38,065 INFO exited: aircast-x86-64 (exit status 1; not expected)
```

Without using `AIRCAT_VAR` this is what I see 

```txt
airconnect    | 2021-06-20 00:05:48,461 CRIT Supervisor running as root (no user in config file)
airconnect    | 2021-06-20 00:05:48,463 INFO supervisord started with pid 289
airconnect    | 2021-06-20 00:05:49,466 INFO spawned: 'airupnp-x86-64' with pid 293
airconnect    | 2021-06-20 00:05:49,468 INFO spawned: 'aircast-x86-64' with pid 294
airconnect    | 2021-06-20 00:05:50,594 INFO success: airupnp-x86-64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
airconnect    | 2021-06-20 00:05:50,595 INFO success: aircast-x86-64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Everything runs fine if I `docker exec` into the container and run it normally.

> NOTE: While I may be a dev with a decade of experience, I have <2 days of docker experience.

**Comment by hipstersmoothie** [comment]
More Context: Seems to only error out when I provide a file path?

Here I try what I saw in other issue in this repo and have the config files outside of the container.

<img width="408" alt="CleanShot 2021-06-19 at 17 16 43@2x" src="https://user-images.githubusercontent.com/1192452/122658437-208ae980-d122-11eb-92d5-11560be42083.png">

```yml
services:
  airconnect:
    image: 1activegeek/airconnect:latest
    container_name: airconnect
    restart: always
    network_mode: host
    environment:
      - AIRCAST_VAR='-x /config/airconnect.xml'
    volumes:
      - /home/andrew/config:/config
```

**Comment by hipstersmoothie** [comment]
And you can see here it runs fine when running in the container manually

<img width="876" alt="CleanShot 2021-06-19 at 17 18 59@2x" src="https://user-images.githubusercontent.com/1192452/122658461-76f82800-d122-11eb-902b-ba556acaed18.png">

**Comment by 1activegeek** [comment]
Interesting. Thanks for the ☕ BTW! My first 2 guesses would be permissions and/or formatting in the compose file. Just for giggles, can you try using a raw Docker command vs the compose and see if it has the same issues? So just drop into the term and use: `docker run -d -e AIRCAST_VAR="-x /config/airconnect.xml" --net=host 1activegeek/airconnect` and see what you come up with. I'll try and re-create on my own in the next day or so.

**Comment by 1activegeek** [comment]
Oh and also, if you can - upload what you have in the airconnect.xml file (bleep out anything sensitive if necessary) and snap a quick view of the permissions in the folder its running from. Based on it having worked from inside the container tells me it shouldn't be the config, and it shouldn't be permissions. But permissions can still be a little whacky in docker and something else could be at play fixing the perms once the container launches vs prior to where the compose is erroring in its execution.

**Comment by hipstersmoothie** [comment]
So I ran this:

```sh
sudo docker run -d -e AIRCAST_VAR="-x /config/airconnect.xml" --net=host -v '/home/andrew/config':'/config' 1activegeek/airconnect
```

and it worked. But running `docker-compose up airconnect` I still get the same issue.

I don't really think it's the config file at this point but here is mine:

<details>
<summary>config</summary>

```
<?xml version="1.0"?>
<aircast>
<common>
<enabled>1</enabled>
<stop_receiver>0</stop_receiver>
<media_volume>0.5000</media_volume>
<latency></latency>
<drift>0</drift>
<codec>flc</codec>
<metadata>1</metadata>
<flush>1</flush>
<artwork></artwork>
</common>
<main_log>info</main_log>
<cast_log>info</cast_log>
<util_log>warn</util_log>
<log_limit>-1</log_limit>
<max_players>32</max_players>
<ports>0:0</ports>
<binding>?</binding>
<device>
<udn>fff26e1911ec5943bab3894a95f3e96f</udn>
<name>Geek hau5 TV</name>
<mac>cc:cc:cc:f4:8d:21</mac>
<enabled>1</enabled>
</device>
<device>
<udn>49e9921c248127a4113cf0eb7674ece9</udn>
<name>STR-DN1080 1CF324+</name>
<mac>cc:cc:4f:35:f2:b5</mac>
<enabled>0</enabled>
</device>
<device>
<udn>54e732485cc8db228cb0da9e16200454</udn>
<name>Master Bathroom Speaker</name>
<mac>cc:cc:de:db:81:eb</mac>
<enabled>1</enabled>
</device>
<device>
<udn>d7866ed77f81dd0165feffa9da9e9928</udn>
<name>Garage TV</name>
<mac>cc:cc:0e:18:ff:b2</mac>
<enabled>1</enabled>
</device>
</aircast>
```

</details>

Here are the permissions for the config folder:

<img width="669" alt="CleanShot 2021-06-20 at 10 53 50@2x" src="https://user-images.githubusercontent.com/1192452/122683709-d7847500-d1b5-11eb-9b71-950e2e511265.png">

**Comment by 1activegeek** [comment]
Ok, so if it worked using the raw socket run command, then it's likely something to do with the compose file. Have you tried using " instead of ' for the variable?

**Comment by 1activegeek** [comment]
Hey just checking in - any luck here? I should be able to make a mock up enviro to test on my own on Thur. Been a bit tied up with a training at work. Ends Thur, but I'll have more time overall as well. Let me know if it's still showing up with an issue.

**Comment by 1activegeek** [comment]
@hipstersmoothie were you able to try the suggestion above? And/or did you get it working? I hadn't gotten a chance to check it out myself. If don't hear back by weekend, I'll close this out. You can always come back and re-open I believe if you're able to test further.

**Comment by 1activegeek** [comment]
Closing due to stale status.

**Comment by martinbrose** [comment]
Just ran into the same problem and the solution is to put the whole environment statement into quotes, like below:

```yaml
services:
  airconnect:
    container_name: airconnect
    image: "1activegeek/airconnect"
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./config:/config/airconnect
    environment:
      - "AIRCAST_VAR=-x /config/airconnect/aircast.xml"
      - "AIRUPNP_VAR=-x /config/airconnect/airupnp.xml"
```
