### ISSUE TITLE
Docker Compose w/ Commands

### ISSUE THREAD

**Issue by spencerthayer** [1activegeek/docker-airconnect#31]
How would I pass the runtime command like `-c <mp3[:<rate>]|flc[:0..9]|wav>` to airconnect using a docker-compose file? The following compose file doesn't seem to work, get's the following error `ifelse: fatal: unable to exec -c: No such file or directory [cmd] -c exited 127`.

```yaml
  airconnect:
    image: 1activegeek/airconnect
    container_name: airconnect
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
    command: -c wav
```

**Comment by 1activegeek** [comment]
consult the compose documentation on specifics - but im fairly certain you will need some sort of quotes or ticks to get the entire command issued - with a space like that, it's not taking the whole command per the message you received.

**Comment by spencerthayer** [comment]
Do you know how I could edit the config.xm file with this installation method?

**Comment by spencerthayer** [comment]
Sure so like the following?

```
  airconnect:
    image: 1activegeek/airconnect
    container_name: airconnect
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
    volumes:
      - /appdata/airconnect:/airconnect
```

When I do that I get an empty directory.
