### ISSUE TITLE
Cannot launch ARM version with new image

### ISSUE THREAD

**Issue by IMNotMax** [1activegeek/docker-airconnect#37]
Hi, 
First, as usual thanx for your amazing work !
I have an issue since the latest-arm image is not available.
Using docker-compose, I run
```
  airconnect:
    image: 1activegeek/airconnect   #1activegeek/airconnect:latest-arm
    restart: always
    network_mode: host
    container_name: airconnect
    environment:
      - TZ=America/Montreal
      - ARCH_VAR=arm
```
But the image only contains -x86-64 version of the binaries. (logs show arm version are missing)

If I clone your repo, and create the image locally, everything works great.

Am I missing something ?
Thank you for your help.

(docker on raspberry pi 3 fully updated)

UPDATE : 
My new docker-compose file : 
```
  airconnect:
#    image: 1activegeek/airconnect
    build:
      context: ./docker-airconnect/
      dockerfile: Dockerfile.armhf
    image: airconnect:Vmax
    restart: always
    network_mode: host
    container_name: airconnect
    environment:
      - TZ=America/Montreal
      - ARCH_VAR=arm
```
Update 2:
For those less "techies":
```
pi@RasPiDomus:~ $ git clone https://github.com/1activegeek/docker-airconnect.git
```
 if "git" is missing on your machine: 
```
$ sudo apt update
$ sudo apt install git
```
if you are using docker-compose file, the above config works if you clone the repo in the same directory your docker-compose.yml is.
if you just use docker instructions, go to the **docker-airconnect** directory and type the instruction below (don't forget the last dot (.))
```
pi@RasPiDomus:~/docker/docker-airconnect $  docker image build -t Your_Image_Name -f /Path/To/Repo/Doeckerfile-armhf .
```
here a working example: 
`pi@RasPiDomus:~/docker/docker-airconnect $  docker image build -t airconnect:test -f /home/pi/docker/docker-airconnect/Dockerfile.armhf .`
