### ISSUE TITLE
INC_MODELNUMBERS not working as expected

### ISSUE THREAD

**Issue by robinwo** [1activegeek/docker-airconnect#44]
Loading Airconnect via docker-compose,
Defined INC_MODELNUMBERS environment variable to **only include my PLAY:3** (S3).
```
  airconnect:
    image: 1activegeek/airconnect
    network_mode: host
    restart: unless-stopped
    environment:
      - SUPPRESS_FLUSH=TRUE
      - INCLUDE_AIRCAST=TRUE
      - INC_MODELNUMBERS=S3
```

Expected behavior is to only list 'Sonos Keuken+' in Airplay devices (via Airconnect), since this is the only PLAY:3 I have in my setup. Actual behavior is all Sonos devices continue to be listed (which are different models than PLAY:3). As a result I'm seeing Airplay 2 supported devices as duplicated.

Is this an issue with the INC_MODELNUMBERS setting, or a configuration problem on my end?

![Screenshot 2022-11-12 at 13 28 04](https://user-images.githubusercontent.com/2698369/201474007-727f60e6-2fab-4b50-bea1-4ca2c14aaf71.png)
