### ISSUE TITLE
Can I have an example of how to create a config file using the docker run command please?

### ISSUE THREAD

**Issue by Abcmsaj** [1activegeek/docker-airconnect#50]
I don't know if I'm being stupid or not - I have created a docker-compose file actually as I wanted an AirConnect directory:

version: '3'

```
services:
  airconnect:
    image: 1activegeek/airconnect:latest
    container_name: airconnect
    restart: unless-stopped
    network_mode: 'host'
```

This works, runs the docker image - but I wanted a way to pull config files from my local directory and have them used inside the container (i.e. I want to increase the volume of everything, change names, etc) - I don't know which dir inside the container that the config files are meant to go. And how are they named so that AirCast and AirUpnp know the difference?

Can't work out how to do it for the life of me so any help would be really appreciated!! Thanks
